config/routes.rb
Rails.application.routes.draw do
  root :to => "players#index"
  resources :players

end

app/models/player.rb
class Player < ActiveRecord::Base
	scope :descending, ->{ order('score desc') }
	scope :ascending, ->{ order('score asc')}
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :score, :numericality => {:only_integer => true}
	
	def show_rank
		records = Player.descending.all
		rank = nil 
		records.each_with_index do |player, index| 			
			if self.id == player.id
				rank = index + 1
			end
		end
		rank
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_found
	  render :file => "#{Rails.root}/public/404.html",  :status => 404
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	
	respond_to :html, :json
	before_action :load_player, only: [:show, :edit, :update, :destroy]

	def index
		@players = Player.descending.all
		respond_with @players		
	end

	def show
		if Player.where(id: @player.id).empty?
			not_found
		else
			respond_with @player
		end
	end

	def new
		@player = Player.new
    	respond_with @player
	end

	def create
	  @player = Player.new(player_params)
	  @player.save
 	  
	  flash[:notice] = 'Player was successfully created.'
	  respond_with @player, :location => players_path	  
	   
	end
	
	def update
		if @player.update(player_params)
		  flash[:notice] = 'Player was successfully updated.'
	    end
	    respond_with @player, :location => players_path
	end

	def destroy
		@player.destroy
		redirect_to :action => 'index'
	end

	private

	  def load_player
	    @player = Player.find(params[:id]) || not_found	    
	  end

	  def player_params
	    params.require(:player).permit(:first_name, :last_name, :score)
	  end

	  rescue_from ActiveRecord::RecordNotFound do
		flash[:notice] = 'The object you tried to access does not exist'
		not_found   # or e.g. redirect_to :action => :index
	   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leaderboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/players/_form.html.erb
<div class="container">
  <%= form_for(@player, html: {role: "form", class: "ma-form"}) do |f| %>

    
    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
    <div class="form-group">
      <%= f.label :score %>
      <%= f.text_field :score %>
    </div>
    <div class="form-actions">
      <%= link_to 'Cancel', players_path, :class => "btn btn-info" %>
      <%= f.submit 'Submit', :class => "btn btn-primary" %>
    </div>

  <% end %>
</div>

app/views/players/edit.html.erb
<div class="container">
	<h1>Edit player</h1>
	<%= render 'form' %>
</div>

app/views/players/index.html.erb
<div class="container">
	<%= link_to 'New Player', new_player_path, :class=>"btn new"%>
	<table class="table table-bordered table-striped">
	  <thead>
	    <tr>
	      <th>
	        Name
	      </th>
	      <th>
	        Score
	      </th>
	      <th>
	      	Rank/Description
	      </th>
	    </tr>
	  </thead>
	  <tbody>
	    <% @players.each_with_index do |player, index| %>
	      <tr data-item-id=<%= "#{player.id}" %> class="item">
	        <td>
	          <%= player.first_name %> <%= player.last_name %>
	        </td>
	        <td>
	          <%= player.score %>
	        </td>
	        <td>
	        	<%= link_to player_path(player), :method => :delete, :data => {:confirm => 'Are you sure?'}, :class => "btn btn-notext pull-right" do %>
		        	<span class="glyphicon glyphicon-remove">Delete</span>
		        <% end %>
		        <%= index+1 %>

		        <%= link_to 'show', player_path(player), :class => 'btn btn-default pull-right' %> 
		        
	        </td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
</div>

app/views/players/new.html.erb
<div class="container">
	<h1>New player</h1>
	<%= render 'form' %>
</div>

app/views/players/show.html.erb
<div class="container">
<%= @player.first_name %> <%= @player.last_name %>
</br>
Score: <%= @player.score %></br>
Rank: <%= @player.show_rank %></br>
<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>
</div>